import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
	variable: "--font-montserrat",
	weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
	title: "Task It",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${montserrat.variable} ${montserrat.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
